### PR TITLE
bugfix(#2): fixing type error in Postgres port

### LINKED ISSUE #2: Bug in Postgres port configuration in dbt profile
There is a bug in the following code snippet in the dbt profile:
```yaml
default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: "{{ env_var('POSTGRES_PORT', 5432) }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: "{{ env_var('POSTGRES_SCHEMA') }}"
```
On line `port: "{{ env_var('POSTGRES_PORT', 5432) }}"`, the system is expecting an integer value for the `POSTGRES_PORT` environment variable, but it is receiving a string, causing a runtime error while reading profiles. 

Error logs:
```sh
17:06:13  Encountered an error while reading profiles:
17:06:13    ERROR: Runtime Error
  Credentials in profile "default", target "dev" invalid: '5432' is not of type 'integer'
17:06:13  Defined profiles:
17:06:13   - default
```
This issue needs to be fixed to ensure the correct configuration of the Postgres port in the dbt profile.

### PR DESCRIPTION
**Pull request by samuelimoisili**
This pull request addresses the bug where the system is expecting a number but received a string in the `port` field of the `outputs` section of the `default` profile in `dbt_project.yml`.

Closes #2

### CODE REVIEW

**Review by andrablaj — APPROVED** [review]

**Review by njogz — APPROVED** [review]

**Comment by njogz** [comment]
@samuelimoisili you should comment and ask reviewers to have another look if the code changes after a review.

**Comment by samuelimoisili** [comment]
Thanks, I'll take that into account on the next merge. I had to merge to run the actions because it triggers on merge. I only made changes to the `.github/workflows/build.yml`.

**Comment by lorerod** [comment]
> Thanks, I'll take that into account on the next merge. I had to merge to run the actions because it triggers on merge. I only made changes to the `.github/workflows/build.yml`.

@samuelimoisili Rather than having to commit/push every time you want to try out the changes you are making to your `.github/workflows/` files, I found [nektos/act](https://github.com/nektos/act) to run the actions locally. I should have taken the time to compare with other similar tools, but for simple workflows it served its purpose.

**Comment by njogz** [comment]
For additional context to my comment: A significant change might introduce bugs, typos, or the need for additional tests or refactors thus the need for reviewers take another look.

**Pull request merged**
